version: '3.8'

services:
  web:
    build: ./net_print_site
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./net_print_site/:/usr/src/net_print_site/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev