# Generated by Django 4.2.7 on 2023-11-09 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('number', models.CharField(max_length=12, verbose_name='Телефон')),
                ('mail', models.CharField(max_length=100, verbose_name='Почта')),
                ('social_nets', models.URLField(verbose_name='Соц.Сети')),
                ('description', models.TimeField(verbose_name='Описание')),
                ('files', models.FileField(upload_to='', verbose_name='Файлы')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Предложения',
            },
        ),
    ]
