# Generated by Django 4.2.7 on 2023-11-09 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offers',
            name='files',
        ),
        migrations.AlterField(
            model_name='offers',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='social_nets',
            field=models.CharField(max_length=127, verbose_name='Соц.Сети'),
        ),
    ]
