# Generated by Django 4.2.7 on 2023-11-09 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_offers_files_alter_offers_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='files',
            field=models.FileField(default=0, upload_to='', verbose_name='Файлы'),
            preserve_default=False,
        ),
    ]
